[package]
name = "opus-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[[bin]]
name = "opus"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap.workspace = true
open.workspace = true
opus-auth = { path = "../auth" }
opus-platform = { path = "../platform" }
opus-engine = { path = "../engine" }
