#!/usr/bin/env bash
set -euo pipefail

opus_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
runtime_artifact_dir="${OPUS_RUNTIME_ARTIFACT_DIR:-${opus_root}/runtime-artifacts}"
bootstrap_destination="${opus_root}/desktop/src-tauri/resources/bootstrap"
mkdir -p "${bootstrap_destination}"
find "${bootstrap_destination}" -mindepth 1 -maxdepth 1 -type f -name '*.jar' -delete

for artifact_name in \
  bootstrap-0.0.1.jar \
  rbw-forge-coremod-0.0.1.jar \
  rbw-forge-client-0.0.1-preview.3.jar; do
  artifact_source="${runtime_artifact_dir}/${artifact_name}"
  if [[ ! -f "${artifact_source}" ]]; then
    echo "Missing Runtime artifact: ${artifact_source}" >&2
    echo "Set OPUS_RUNTIME_ARTIFACT_DIR to a verified Runtime artifact directory." >&2
    exit 1
  fi
  cp "${artifact_source}" "${bootstrap_destination}/${artifact_name}"
done

verify_artifact() {
  local artifact_path="$1"
  local expected_sha1="$2"
  local expected_size="$3"
  if [[ ! -f "${artifact_path}" ]]; then
    echo "Missing reviewed Opus artifact: ${artifact_path}" >&2
    exit 1
  fi
  local actual_sha1
  local actual_size
  actual_sha1="$(shasum -a 1 "${artifact_path}" | cut -d ' ' -f 1)"
  actual_size="$(wc -c < "${artifact_path}" | tr -d '[:space:]')"
  if [[ "${actual_sha1}" != "${expected_sha1}" || "${actual_size}" != "${expected_size}" ]]; then
    echo "Reviewed Opus artifact changed: ${artifact_path}" >&2
    echo "expected SHA-1=${expected_sha1} size=${expected_size}" >&2
    echo "actual   SHA-1=${actual_sha1} size=${actual_size}" >&2
    exit 1
  fi
}

# Keep the generated bytes and the runtime integrity contract in lockstep.
# Updating either artifact requires an intentional lock review in forge.rs.
verify_artifact \
  "${bootstrap_destination}/rbw-forge-coremod-0.0.1.jar" \
  "689ad5b76e1749e2be8ce91488b3a26669aba079" \
  "101474"
verify_artifact \
  "${bootstrap_destination}/rbw-forge-client-0.0.1-preview.3.jar" \
  "b5edc2d61edb6d116984859f283407d7940f675e" \
  "255915"

brand_destination="${opus_root}/desktop/src-tauri/resources/brand"
mkdir -p "${brand_destination}"
cp "${opus_root}/desktop/public/brand/opus-wordmark-transparent.png" \
  "${brand_destination}/opus-wordmark-transparent.png"
