#!/usr/bin/env bash
set -euo pipefail

rbw_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

"${rbw_root}/game/gradlew" -p "${rbw_root}/game" prepareBootstrap

bootstrap_source="${rbw_root}/game/build/bootstrap"
bootstrap_destination="${rbw_root}/desktop/src-tauri/resources/bootstrap"
mkdir -p "${bootstrap_destination}"
find "${bootstrap_destination}" -mindepth 1 -maxdepth 1 -type f -name '*.jar' -delete
cp "${bootstrap_source}"/*.jar "${bootstrap_destination}/"

verify_artifact() {
  local artifact_path="$1"
  local expected_sha1="$2"
  local expected_size="$3"
  if [[ ! -f "${artifact_path}" ]]; then
    echo "Missing reviewed RBW artifact: ${artifact_path}" >&2
    exit 1
  fi
  local actual_sha1
  local actual_size
  actual_sha1="$(shasum -a 1 "${artifact_path}" | cut -d ' ' -f 1)"
  actual_size="$(wc -c < "${artifact_path}" | tr -d '[:space:]')"
  if [[ "${actual_sha1}" != "${expected_sha1}" || "${actual_size}" != "${expected_size}" ]]; then
    echo "Reviewed RBW artifact changed: ${artifact_path}" >&2
    echo "expected SHA-1=${expected_sha1} size=${expected_size}" >&2
    echo "actual   SHA-1=${actual_sha1} size=${actual_size}" >&2
    exit 1
  fi
}

# Keep the generated bytes and the runtime integrity contract in lockstep.
# Updating either artifact requires an intentional lock review in forge.rs.
verify_artifact \
  "${bootstrap_destination}/rbw-forge-coremod-0.0.1.jar" \
  "5d4e44450083b28559d067ccf7f53ab2b73b9984" \
  "101444"
verify_artifact \
  "${bootstrap_destination}/rbw-forge-client-0.0.1-preview.3.jar" \
  "07b137286bf10e4459405a775b36374730e597c9" \
  "335621"

brand_destination="${rbw_root}/desktop/src-tauri/resources/brand"
mkdir -p "${brand_destination}"
cp "${rbw_root}/desktop/public/brand/rbw-wordmark-transparent.png" \
  "${brand_destination}/rbw-wordmark-transparent.png"
